#!/bin/bash
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune0;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune1;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune2;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune3;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune4;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune5;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune6;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune7;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune8;
scancel -n /project/def-aloise/rmoine/launches/finetune/finetune9;