#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus-per-node=v100l:1 # on cedar choose one v100l gpu but can be also p100l
#SBATCH --cpus-per-task=1 # change this parameter to 2,4,6,... and increase "--num_workers" accordingly to see the effect on performance
#SBATCH --time=00-01:00:00           # duration (JJ-HH:MM:SS)
#SBATCH --output=log-%x-%j.out
#SBATCH --error=log-%x-%j.err
#SBATCH --mail-user=robin.moine456@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --mem=8G # Request 8 GB of RAM

# syntax of 
# Capture the start time
start_time=$(date +"%Y-%m-%d %H:%M:%S")

# loading modules
module load python/3.9
module load cuda/11.7
nvidia-smi


module load StdEnv/2020  gcc/9.3.0  cuda/11.4 python/3.11 arrow ## cuda/11.7 not work
virtualenv $SLURM_TMPDIR/MYENV
source $SLURM_TMPDIR/MYENV/bin/activate
pip install --no-index --upgrade pip

pip install $HOME/docstring_parser-0.15-py3-none-any.whl --no-index
pip install $HOME/shtab-1.6.4-py3-none-any.whl --no-index
pip install $HOME/tyro-0.5.10-py3-none-any.whl --no-index
pip install $HOME/trl-0.7.2-py3-none-any.whl --no-index


pip install peft --no-index
pip install scikit-learn bitsandbytes sentencepiece protobuf tqdm nltk --no-index
pip install huggingface_hub --no-index
pip install datasets --no-index

pip install xformers accelerate --no-index
pip install seaborn --no-index
pip install transformers --no-index
pip install torch --no-index
pip install h5py --no-index
pip install fire --no-index
pip install optuna --no-index

# Execution of the script: replace by python path_to_your_script
# Do not forget to change the pathes to absolute pathes (dont hesitate to use $USER variable)
folder_embeddings=/project/def-aloise/$USER/data/embeddings/embeddings_eclipse_72k_1000_meta-llama--Llama-2-13b-chat-hf/
path_dst=/project/def-aloise/$USER/data/embeddings_eclipse_72k.hdf5
base_name_hdf5=embeddings_chunk_eclipse_72k_1000_meta-llama--Llama-2-13b-chat-hf_
base_name_missing=missing_eclipse_72k_1000_meta-llama--Llama-2-13b-chat-hf_

python /project/def-aloise/$USER/main.py merge_data_embeddings --folder_embeddings=$folder_embeddings --path_dst=$path_dst --base_name_hdf5=$base_name_hdf5 --base_name_missing=$base_name_missing


# Capture the end time
end_time=$(date +"%Y-%m-%d %H:%M:%S")

# Calculate and display the execution time
start_seconds=$(date -d "$start_time" '+%s')
end_seconds=$(date -d "$end_time" '+%s')
execution_time=$((end_seconds - start_seconds))

echo "Execution time: $execution_time seconds"

