#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=3
#SBATCH --time=03-0:0:0 
#SBATCH --output=log-%x-%j.out
#SBATCH --error=log-%x-%j.err
#SBATCH --mail-user=robin.moine456@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --mem=128G

start_time=$(date +"%Y-%m-%d %H:%M:%S")

module load StdEnv/2020  gcc/9.3.0  cuda/11.4 arrow python/3.10.2 cudnn
virtualenv $SLURM_TMPDIR/MYENV
source $SLURM_TMPDIR/MYENV/bin/activate

pip install numpy scikit-learn tqdm nltk --no-index
pip install seaborn --no-index
pip install matplotlib --no-index
pip install pandas --no-index
pip install h5py --no-index
pip install fire --no-index
pip install optuna --no-index

script="/project/def-aloise/$USER/baseline_functions.py"
algorithm=SVC
dataset=eclipse_72k
id_job="_$SLURM_JOB_ID"
python $script launch_search --algorithm=$algorithm --dataset=$dataset --num_jobs=2 --num_samples=2000 --id_job=$id_job

end_time=$(date +"%Y-%m-%d %H:%M:%S")
start_seconds=$(date -d "$start_time" '+%s')
end_seconds=$(date -d "$end_time" '+%s')
execution_time=$((end_seconds - start_seconds))
echo "Execution time: $execution_time seconds"