#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gres=gpu:1 # request a GPU
#SBATCH --cpus-per-task=1 # change this parameter to 2,4,6,... and increase "--num_workers" accordingly to see the effect on performance
#SBATCH --time=00:00:10           # duration (JJ-HH:MM:SS)
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.out
#SBATCH --mail-user=email_address
#SBATCH --mail-type=ALL
#SBATCH --mem=8GB

# syntax of 
# Capture the start time
start_time=$(date +"%Y-%m-%d %H:%M:%S")

# loading modules
module load python/3.9
virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
pip install torch transformers accelerate huggingface_hub --no-index

# Execution of the script: replace by python path_to_your_script
# Do not forget to change the pathes to absolute pathes (dont hesitate to use $USER variable)
python /project/def-aloise/$USER/main.py


# Capture the end time
end_time=$(date +"%Y-%m-%d %H:%M:%S")

# Calculate and display the execution time
start_seconds=$(date -d "$start_time" '+%s')
end_seconds=$(date -d "$end_time" '+%s')
execution_time=$((end_seconds - start_seconds))

echo "Execution time: $execution_time seconds"